name: Java CI with Gradle

on:
  push:
    branches: [ master, feat/leveldb-performance ]
  pull_request:
    branches: [ master ]

jobs:
  linux-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: chmod +x gradlew

      - name: Build natives + publish
        run: ./gradlew publish
        env:
          CC: gcc
          ci: true
          PNX_REPO_USERNAME: ${{ secrets.PNX_REPO_USERNAME }}
          PNX_REPO_PASSWORD: ${{ secrets.PNX_REPO_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: Linux-amd64
          path: ./tmp/compiled/linux/amd64/libdeflate_jni.so


  windows-amd64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build natives
        run: ./gradlew compileNatives
        env:
          MSVC: true

      - uses: actions/upload-artifact@v4
        with:
          name: Windows-amd64
          path: ./tmp/compiled/windows/amd64/libdeflate_jni.dll
